language: android
android:
  components:
    - platform-tools
    - tools
    - build-tools-28
    - android-28
    - extra-android-support
    - extra-android-m2repository

before_install:
  - yes | sdkmanager "platforms;android-27"
  
before_script:
    - chmod +x gradlew

script:
    ./gradlew build