language: android
jdk: oraclejdk8
android:
  components:
    - platform-tools
    - tools
    - build-tools-28
    - android-28
    - extra-android-support
    - extra-android-m2repository
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_script:
    - mkdir -p "$ANDROID_HOME/licenses"
    - cp ./google-licenses/* "$ANDROID_HOME/licenses/"
    - chmod +x gradlew

script:
    ./gradlew build